### ISSUE TITLE
Sound Effects: An unhandled error has occured

### ISSUE THREAD

**Issue by bleedingfawn** [ikno-the-box-guy/IkSound#1]
Heya, I love this project.
Unfortunately I've started getting "An unhandled error has occured" message whenever I try to go to any sound category under Sound Effects tab. Music library seems to be working fine still, it's just the sound effects that I can no longer view. Is this a temporary issue or is this something that needs to be fixed in the site's code?
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: DeserializeUnableToConvertValue, System.DateTime Path: $.entities.tracks.237191.releaseDate | LineNumber: 0 | BytePositionInLine: 1296.
System.Text.Json.JsonException: DeserializeUnableToConvertValue, System.DateTime Path: $.entities.tracks.237191.releaseDate | LineNumber: 0 | BytePositionInLine: 1296.
 ---> System.InvalidOperationException: InvalidCast, Null, string
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType )
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& )
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.DateTimeConverter.Read(Utf8JsonReader& , Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.DateTime, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[IkSound.Models.Epidemic.Song, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Song& )
   at System.Text.Json.Serialization.JsonConverter`1[[IkSound.Models.Epidemic.Song, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Song& , Boolean& )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[IkSound.Models.Epidemic.Song, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[IkSound.Models.Epidemic.Song, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[IkSound.Models.Epidemic.Song, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& , Boolean& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[IkSound.Models.Epidemic.Song, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[IkSound.Models.Epidemic.Entities, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Entities& )
   at System.Text.Json.Serialization.JsonConverter`1[[IkSound.Models.Epidemic.Entities, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Entities& , Boolean& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[IkSound.Models.Epidemic.Entities, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[IkSound.Models.Epidemic.Root, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Root& )
   at System.Text.Json.Serialization.JsonConverter`1[[IkSound.Models.Epidemic.Root, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Root& , Boolean& )
   at System.Text.Json.Serialization.JsonConverter`1[[IkSound.Models.Epidemic.Root, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , Utf8JsonReader& , Exception )
   at System.Text.Json.Serialization.JsonConverter`1[[IkSound.Models.Epidemic.Root, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[IkSound.Models.Epidemic.Root, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ContinueDeserialize(ReadBufferState& , JsonReaderState& , ReadStack& )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<DeserializeAsync>d__1[[IkSound.Models.Epidemic.Root, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<<FromJsonAsyncCore>g__Core|12_0>d`2[[IkSound.Models.Epidemic.Root, IkSound, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Text.Json.JsonSerializerOptions, System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
   at IkSound.Components.SearchComponent.LoadSongs()
   at IkSound.Components.SearchComponent.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
Dt @ blazor.webassembly.js:1

```

**Comment by bleedingfawn** [comment]
Woah, thanks for fixing it so fast, appreciate it a lot!

**Comment by erwtj** [comment]
Glad you like it! Let me know if there are any other issues you'd like me to fix 👍
