### ISSUE TITLE
Sound Effects: No genre throws exception

### ISSUE THREAD

**Issue by erwtj** [ikno-the-box-guy/IkSound#2]
When browsing sound effects, a sound effect may come by that doesn't have a genre associated with it. This causes the following error to appear in the browser console:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: NoElements
System.InvalidOperationException: NoElements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Genre](IEnumerable`1 )
   at IkSound.Components.SongCard.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

This can be fixed by first checking the length of the genre list before indexing it directly.

An example of this error can be found at this url [https://ikno-the-box-guy.github.io/IkSound/search?Term=sting&Sfx=True](https://ikno-the-box-guy.github.io/IkSound/search?Term=sting&Sfx=True)

**Comment by erwtj** [comment]
Solved by commit 0d49f2d
